version: "3"

services:
  kafka:
    depends_on:
    - zookeeper
    image: mc.varun/kafka:latest
    ports:
    - 9092:9092

  zookeeper:
    image: mc.varun/zookeeper:latest
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
