version: "2"

services:
  zookeeper:
    image: mc.varun/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080

  platform:
    depends_on:
      - zookeeper
    image: busybox:latest
