version: "2"

services:
  zookeeper:
    image: 497513737772.dkr.ecr.us-east-1.amazonaws.com/mc.varun/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
