version: "3"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - 8081:8081

  platform:
    depends_on:
      - artifactory
    image: busybox:latest
