version: "2"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
    - 8081:8081

  kafka:
    depends_on:
    - zookeeper
    image: 497513737772.dkr.ecr.us-east-1.amazonaws.com/mc.varun/kafka:latest

  zookeeper:
    image: 497513737772.dkr.ecr.us-east-1.amazonaws.com/mc.varun/zookeeper:latest
